"""Updated tables

Revision ID: 1dd118016700
Revises: 3437fac4069e
Create Date: 2025-05-12 22:21:46.008040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd118016700'
down_revision: Union[str, None] = '3437fac4069e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('attendances', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.create_foreign_key('attendances_student_id_fkey', 'attendances', 'students', ['student_id'], ['id'])
    op.drop_column('attendances', 'mosque_id')
    op.drop_column('attendances', 'user_id')
    op.drop_column('attendances', 'user_type')
    # ### end Alembic commands ###
