"""Updated tables

Revision ID: 28aa941174fc
Revises: 9d63efef347d
Create Date: 2025-05-08 22:50:58.056053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28aa941174fc'
down_revision: Union[str, None] = '9d63efef347d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circle_students', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('active', 'inactive', 'graduated', name='circlestudentstatus'),
               existing_nullable=True)
    op.create_index(op.f('ix_circle_students_circle_id'), 'circle_students', ['circle_id'], unique=False)
    op.create_index(op.f('ix_circle_students_student_id'), 'circle_students', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circle_students_student_id'), table_name='circle_students')
    op.drop_index(op.f('ix_circle_students_circle_id'), table_name='circle_students')
    op.alter_column('circle_students', 'status',
               existing_type=sa.Enum('active', 'inactive', 'graduated', name='circlestudentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
