"""Updated tables

Revision ID: 4ddfdead54aa
Revises: a16a43a4b611
Create Date: 2025-05-12 22:46:16.778007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddfdead54aa'
down_revision: Union[str, None] = 'a16a43a4b611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendances', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'attendances', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('attendances', 'user_id')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circle_students', 'status',
               existing_type=sa.Enum('active', 'inactive', 'graduated', name='circlestudentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('attendances', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'teacher_id')
    op.drop_column('attendances', 'student_id')
    # ### end Alembic commands ###
