"""Updated tables

Revision ID: 61e3d2a3386e
Revises: 01ecba386fad
Create Date: 2025-05-12 23:27:40.506089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e3d2a3386e'
down_revision: Union[str, None] = '01ecba386fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('students_preferred_circle_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'preferred_circle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('preferred_circle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('students_preferred_circle_id_fkey', 'students', 'study_circles', ['preferred_circle_id'], ['id'])
    op.alter_column('circle_students', 'status',
               existing_type=sa.Enum('active', 'inactive', 'graduated', name='circlestudentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
