"""Modify tables

Revision ID: 9bcb1786afa6
Revises: 61e3d2a3386e
Create Date: 2025-05-12 23:29:56.754429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcb1786afa6'
down_revision: Union[str, None] = '61e3d2a3386e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circle_students', 'status',
               existing_type=sa.Enum('active', 'inactive', 'graduated', name='circlestudentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
