"""Updated tables

Revision ID: a9c37f590977
Revises: 
Create Date: 2025-05-07 17:16:14.111888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c37f590977'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'created_at')
    op.drop_column('attendances', 'updated_at')
    op.drop_column('circle_students', 'created_at')
    op.drop_column('circle_students', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circle_students', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('circle_students', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
