"""Updated tables

Revision ID: e393a90a6946
Revises: d20816c33362
Create Date: 2025-05-04 14:24:35.023054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e393a90a6946'
down_revision: Union[str, None] = 'd20816c33362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'updated_at')
    op.drop_column('centers', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('centers', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
